export const REVIEWSOFSINGLEPRODUCT_REQUEST = "REVIEWSOFSINGLEPRODUCT_REQUEST";
export const REVIEWSOFSINGLEPRODUCT_SUCCESS = "REVIEWSOFSINGLEPRODUCT_SUCCESS";
export const REVIEWSOFSINGLEPRODUCT_FAIL = "REVIEWSOFSINGLEPRODUCT_FAIL";

export const CREATEREVIEW_REQUEST = "CREATEREVIEW_REQUEST";
export const CREATEREVIEW_SUCCESS = "CREATEREVIEW_SUCCESS";
export const CREATEREVIEW_FAIL = "CREATEREVIEW_FAIL";

export const DELETEREVIEW_REQUEST = "DELETEREVIEW_REQUEST";
export const DELETEREVIEW_SUCCESS = "DELETEREVIEW_SUCCESS";
export const DELETEREVIEW_FAIL = "DELETEREVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";